'use client';

import React, { useState } from 'react';

export default function QuestionUploadForm({ onSubmit }) {
  const [question, setQuestion] = useState('');
  const [file, setFile] = useState(null);

  const handleSubmit = (e) => {
    e.preventDefault();
    const newEntry = {
      question,
      fileName: file?.name || 'No file',
      date: new Date().toLocaleString(),
      aiResponse: 'This will be generated by AI (coming soon)'
    };
    onSubmit(newEntry);
    setQuestion('');
    setFile(null);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <textarea
        value={question}
        onChange={(e) => setQuestion(e.target.value)}
        placeholder="Write your question here..."
        required
        className="w-full h-24 p-3 border rounded-md resize-none focus:ring-2 focus:ring-blue-500"
      />
      <input
        type="file"
        onChange={(e) => setFile(e.target.files[0])}
        className="block w-full"
      />
      <button
        type="submit"
        className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-md transition"
      >
        Get AI Answer
      </button>
    </form>
  );
}
